steps:
# Install dependencies
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']

# Build the React client
- name: 'node:18'
  dir: 'client'
  entrypoint: 'npm'
  args: ['run', 'build']

# Build and copy React app to server
- name: 'node:18'
  entrypoint: 'npm'
  args: ['run', 'build']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_SERVICE'
  - '--region'
  - '$_REGION'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'NODE_ENV=production,PORT=8080'
  - '--set-secrets'
  - 'OPENROUTER_API_KEY=openrouter-api-key:latest'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'

images:
- 'gcr.io/$PROJECT_ID/$_SERVICE'